# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.txauth import tariff_pb2 as proto_dot_common_dot_tariff__pb2
from protos.txauth import account_id_pb2 as proto_dot_common_dot_account__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/account.proto',
  package='proto.common',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\013ProtoCommon'),
  serialized_pb=_b('\n\x1aproto/common/account.proto\x12\x0cproto.common\x1a\x19proto/common/tariff.proto\x1a\x1dproto/common/account_id.proto\"\xd6\x06\n\x07\x41\x63\x63ount\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x17.proto.common.AccountId\x12\x0c\n\x04\x64\x65mo\x18\x02 \x01(\x08\x12\x10\n\x08readonly\x18\x03 \x01(\x08\x12(\n\x04type\x18\x04 \x01(\x0e\x32\x1a.proto.common.Account.Type\x12+\n\x0csub_accounts\x18\x05 \x03(\x0b\x32\x15.proto.common.Account\x12\x34\n\x0border_types\x18\x06 \x03(\x0e\x32\x1f.proto.common.Account.OrderType\x12\x0b\n\x03iis\x18\x07 \x01(\x08\x12)\n\x07tariffs\x18\x08 \x03(\x0b\x32\x14.proto.common.TariffB\x02\x18\x01\x12\x33\n\x06status\x18\t \x01(\x0e\x32#.proto.common.Account.AccountStatus\x12\x39\n\nproperties\x18\n \x03(\x0b\x32%.proto.common.Account.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"~\n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03MMA\x10\x01\x12\x08\n\x04\x45TNA\x10\x02\x12\t\n\x05MICEX\x10\x03\x12\x12\n\x0eMICEX_CURRENCY\x10\x04\x12\t\n\x05\x46ORTS\x10\x05\x12\t\n\x05UNION\x10\x06\x12\t\n\x05SPBEX\x10\x07\x12\x07\n\x03USA\x10\x08\x12\x0b\n\x07SPECULO\x10\t\"\"\n\tOrderType\x12\n\n\x06MARKET\x10\x00\x12\t\n\x05LIMIT\x10\x01\"d\n\rAccountStatus\x12\x12\n\x0e\x41\x43\x43OUNT_ACTIVE\x10\x00\x12\x16\n\x12\x41\x43\x43OUNT_RESTRICTED\x10\n\x12\x13\n\x0f\x41\x43\x43OUNT_BLOCKED\x10\x14\x12\x12\n\x0e\x41\x43\x43OUNT_CLOSED\x10\x1e\"\x93\x01\n\x11\x41\x63\x63ountProperties\x12\x11\n\rCRYPTO_WALLET\x10\x00\x12\x0f\n\x0bMARGIN_TYPE\x10\x01\x12\x16\n\x12\x41\x43TIVE_TARIFF_CODE\x10\x02\x12\x10\n\x0cPROP_TRADING\x10\x03\x12\x12\n\x0eOLD_TRADE_CODE\x10\x04\x12\x0e\n\nREG_NUMBER\x10\x05\x12\x0c\n\x08REG_DATE\x10\x06\x42\x10P\x01\xa2\x02\x0bProtoCommonb\x06proto3')
  ,
  dependencies=[proto_dot_common_dot_tariff__pb2.DESCRIPTOR,proto_dot_common_dot_account__id__pb2.DESCRIPTOR,])



_ACCOUNT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='proto.common.Account.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MMA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETNA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICEX', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICEX_CURRENCY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORTS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNION', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPBEX', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USA', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECULO', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=543,
  serialized_end=669,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNT_TYPE)

_ACCOUNT_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='proto.common.Account.OrderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARKET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIMIT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=671,
  serialized_end=705,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNT_ORDERTYPE)

_ACCOUNT_ACCOUNTSTATUS = _descriptor.EnumDescriptor(
  name='AccountStatus',
  full_name='proto.common.Account.AccountStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_ACTIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_RESTRICTED', index=1, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_BLOCKED', index=2, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_CLOSED', index=3, number=30,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=707,
  serialized_end=807,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNT_ACCOUNTSTATUS)

_ACCOUNT_ACCOUNTPROPERTIES = _descriptor.EnumDescriptor(
  name='AccountProperties',
  full_name='proto.common.Account.AccountProperties',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CRYPTO_WALLET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARGIN_TYPE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE_TARIFF_CODE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROP_TRADING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OLD_TRADE_CODE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REG_NUMBER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REG_DATE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=810,
  serialized_end=957,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNT_ACCOUNTPROPERTIES)


_ACCOUNT_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='proto.common.Account.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.common.Account.PropertiesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.common.Account.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=541,
)

_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='proto.common.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.common.Account.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demo', full_name='proto.common.Account.demo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readonly', full_name='proto.common.Account.readonly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.common.Account.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_accounts', full_name='proto.common.Account.sub_accounts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_types', full_name='proto.common.Account.order_types', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iis', full_name='proto.common.Account.iis', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariffs', full_name='proto.common.Account.tariffs', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.common.Account.status', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='proto.common.Account.properties', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ACCOUNT_PROPERTIESENTRY, ],
  enum_types=[
    _ACCOUNT_TYPE,
    _ACCOUNT_ORDERTYPE,
    _ACCOUNT_ACCOUNTSTATUS,
    _ACCOUNT_ACCOUNTPROPERTIES,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=957,
)

_ACCOUNT_PROPERTIESENTRY.containing_type = _ACCOUNT
_ACCOUNT.fields_by_name['id'].message_type = proto_dot_common_dot_account__id__pb2._ACCOUNTID
_ACCOUNT.fields_by_name['type'].enum_type = _ACCOUNT_TYPE
_ACCOUNT.fields_by_name['sub_accounts'].message_type = _ACCOUNT
_ACCOUNT.fields_by_name['order_types'].enum_type = _ACCOUNT_ORDERTYPE
_ACCOUNT.fields_by_name['tariffs'].message_type = proto_dot_common_dot_tariff__pb2._TARIFF
_ACCOUNT.fields_by_name['status'].enum_type = _ACCOUNT_ACCOUNTSTATUS
_ACCOUNT.fields_by_name['properties'].message_type = _ACCOUNT_PROPERTIESENTRY
_ACCOUNT_TYPE.containing_type = _ACCOUNT
_ACCOUNT_ORDERTYPE.containing_type = _ACCOUNT
_ACCOUNT_ACCOUNTSTATUS.containing_type = _ACCOUNT
_ACCOUNT_ACCOUNTPROPERTIES.containing_type = _ACCOUNT
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ACCOUNT_PROPERTIESENTRY,
    '__module__' : 'proto.common.account_pb2'
    # @@protoc_insertion_point(class_scope:proto.common.Account.PropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'proto.common.account_pb2'
  # @@protoc_insertion_point(class_scope:proto.common.Account)
  })
_sym_db.RegisterMessage(Account)
_sym_db.RegisterMessage(Account.PropertiesEntry)


DESCRIPTOR._options = None
_ACCOUNT_PROPERTIESENTRY._options = None
_ACCOUNT.fields_by_name['tariffs']._options = None
# @@protoc_insertion_point(module_scope)
