# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/account_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/account_id.proto',
  package='proto.common',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\013ProtoCommon'),
  serialized_pb=_b('\n\x1dproto/common/account_id.proto\x12\x0cproto.common\":\n\tAccountId\x12\x12\n\ntrade_code\x18\x01 \x01(\t\x12\x19\n\x11trade_system_name\x18\x02 \x01(\tB\x10P\x01\xa2\x02\x0bProtoCommonb\x06proto3')
)




_ACCOUNTID = _descriptor.Descriptor(
  name='AccountId',
  full_name='proto.common.AccountId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade_code', full_name='proto.common.AccountId.trade_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_system_name', full_name='proto.common.AccountId.trade_system_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['AccountId'] = _ACCOUNTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountId = _reflection.GeneratedProtocolMessageType('AccountId', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTID,
  '__module__' : 'proto.common.account_id_pb2'
  # @@protoc_insertion_point(class_scope:proto.common.AccountId)
  })
_sym_db.RegisterMessage(AccountId)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
