# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/txauth/device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/txauth/device.proto',
  package='proto.txauth',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\003FNM'),
  serialized_pb=_b('\n\x19proto/txauth/device.proto\x12\x0cproto.txauth\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n\x0cLoggedDevice\x12\x32\n\x04info\x18\x01 \x03(\x0b\x32$.proto.txauth.LoggedDevice.InfoEntry\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tremote_ip\x18\x04 \x01(\t\x12+\n\x07updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08provider\x18\x06 \x01(\t\x12\x10\n\x08verified\x18\x07 \x01(\x08\x12\x0e\n\x06key_id\x18\x08 \x01(\t\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x02\x10\x03\"\x83\x01\n\x06\x44\x65vice\x12\x10\n\x08local_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x04info\x18\x03 \x03(\x0b\x32\x1e.proto.txauth.Device.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xd2\x03\n\rDeviceInfoKey\x12\x0c\n\x08PLATFORM\x10\x00\x12\n\n\x06VENDOR\x10\x01\x12\t\n\x05MODEL\x10\x02\x12\x0e\n\nOS_VERSION\x10\x03\x12\r\n\tAPI_LEVEL\x10\x04\x12\x0c\n\x08\x42UILD_ID\x10\x05\x12\x0f\n\x0b\x46INGERPRINT\x10\x06\x12\x0e\n\nANDROID_ID\x10\x07\x12\x11\n\rSERIAL_NUMBER\x10\x08\x12\n\n\x06ROOTED\x10\t\x12\x15\n\x11SCREEN_RESOLUTION\x10\n\x12\x07\n\x03RAM\x10\x0b\x12\x12\n\x0eSTORAGE_VOLUME\x10\x0c\x12\r\n\tCPU_MODEL\x10\r\x12\x0c\n\x08\x43PU_ARCH\x10\x0e\x12\r\n\tCPU_COUNT\x10\x0f\x12\x0e\n\nGPU_VENDOR\x10\x10\x12\x10\n\x0cGPU_RENDERER\x10\x11\x12\x08\n\x04IMEI\x10\x13\x12\x0b\n\x07\x43\x41RRIER\x10\x14\x12\x10\n\x0c\x43\x41RRIER_CODE\x10\x15\x12\x13\n\x0f\x43\x41RRIER_COUNTRY\x10\x16\x12\x08\n\x04LANG\x10\x17\x12\x0c\n\x08TIMEZONE\x10\x18\x12\x0b\n\x07\x43OUNTRY\x10\x19\x12\x0c\n\x08\x41PP_NAME\x10\x1a\x12\x0f\n\x0b\x41PP_VERSION\x10\x1b\x12\x19\n\x15PLAY_SERVICES_VERSION\x10\x1c\x12\x10\n\x0cOS_USER_NAME\x10\x1d\x42\x08P\x01\xa2\x02\x03\x46NMb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_DEVICEINFOKEY = _descriptor.EnumDescriptor(
  name='DeviceInfoKey',
  full_name='proto.txauth.DeviceInfoKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLATFORM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VENDOR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODEL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OS_VERSION', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='API_LEVEL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUILD_ID', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINGERPRINT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID_ID', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERIAL_NUMBER', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROOTED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCREEN_RESOLUTION', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAM', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORAGE_VOLUME', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPU_MODEL', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPU_ARCH', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPU_COUNT', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPU_VENDOR', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPU_RENDERER', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMEI', index=18, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARRIER', index=19, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARRIER_CODE', index=20, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARRIER_COUNTRY', index=21, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LANG', index=22, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEZONE', index=23, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COUNTRY', index=24, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APP_NAME', index=25, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APP_VERSION', index=26, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY_SERVICES_VERSION', index=27, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OS_USER_NAME', index=28, number=29,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=461,
  serialized_end=927,
)
_sym_db.RegisterEnumDescriptor(_DEVICEINFOKEY)

DeviceInfoKey = enum_type_wrapper.EnumTypeWrapper(_DEVICEINFOKEY)
PLATFORM = 0
VENDOR = 1
MODEL = 2
OS_VERSION = 3
API_LEVEL = 4
BUILD_ID = 5
FINGERPRINT = 6
ANDROID_ID = 7
SERIAL_NUMBER = 8
ROOTED = 9
SCREEN_RESOLUTION = 10
RAM = 11
STORAGE_VOLUME = 12
CPU_MODEL = 13
CPU_ARCH = 14
CPU_COUNT = 15
GPU_VENDOR = 16
GPU_RENDERER = 17
IMEI = 19
CARRIER = 20
CARRIER_CODE = 21
CARRIER_COUNTRY = 22
LANG = 23
TIMEZONE = 24
COUNTRY = 25
APP_NAME = 26
APP_VERSION = 27
PLAY_SERVICES_VERSION = 28
OS_USER_NAME = 29



_LOGGEDDEVICE_INFOENTRY = _descriptor.Descriptor(
  name='InfoEntry',
  full_name='proto.txauth.LoggedDevice.InfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.txauth.LoggedDevice.InfoEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.txauth.LoggedDevice.InfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=318,
)

_LOGGEDDEVICE = _descriptor.Descriptor(
  name='LoggedDevice',
  full_name='proto.txauth.LoggedDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='proto.txauth.LoggedDevice.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.txauth.LoggedDevice.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_ip', full_name='proto.txauth.LoggedDevice.remote_ip', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='proto.txauth.LoggedDevice.updated', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provider', full_name='proto.txauth.LoggedDevice.provider', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verified', full_name='proto.txauth.LoggedDevice.verified', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_id', full_name='proto.txauth.LoggedDevice.key_id', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOGGEDDEVICE_INFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=324,
)


_DEVICE_INFOENTRY = _descriptor.Descriptor(
  name='InfoEntry',
  full_name='proto.txauth.Device.InfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.txauth.Device.InfoEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.txauth.Device.InfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=318,
)

_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='proto.txauth.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_id', full_name='proto.txauth.Device.local_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.txauth.Device.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='proto.txauth.Device.info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEVICE_INFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=458,
)

_LOGGEDDEVICE_INFOENTRY.containing_type = _LOGGEDDEVICE
_LOGGEDDEVICE.fields_by_name['info'].message_type = _LOGGEDDEVICE_INFOENTRY
_LOGGEDDEVICE.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DEVICE_INFOENTRY.containing_type = _DEVICE
_DEVICE.fields_by_name['info'].message_type = _DEVICE_INFOENTRY
DESCRIPTOR.message_types_by_name['LoggedDevice'] = _LOGGEDDEVICE
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.enum_types_by_name['DeviceInfoKey'] = _DEVICEINFOKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoggedDevice = _reflection.GeneratedProtocolMessageType('LoggedDevice', (_message.Message,), {

  'InfoEntry' : _reflection.GeneratedProtocolMessageType('InfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _LOGGEDDEVICE_INFOENTRY,
    '__module__' : 'proto.txauth.device_pb2'
    # @@protoc_insertion_point(class_scope:proto.txauth.LoggedDevice.InfoEntry)
    })
  ,
  'DESCRIPTOR' : _LOGGEDDEVICE,
  '__module__' : 'proto.txauth.device_pb2'
  # @@protoc_insertion_point(class_scope:proto.txauth.LoggedDevice)
  })
_sym_db.RegisterMessage(LoggedDevice)
_sym_db.RegisterMessage(LoggedDevice.InfoEntry)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {

  'InfoEntry' : _reflection.GeneratedProtocolMessageType('InfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICE_INFOENTRY,
    '__module__' : 'proto.txauth.device_pb2'
    # @@protoc_insertion_point(class_scope:proto.txauth.Device.InfoEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'proto.txauth.device_pb2'
  # @@protoc_insertion_point(class_scope:proto.txauth.Device)
  })
_sym_db.RegisterMessage(Device)
_sym_db.RegisterMessage(Device.InfoEntry)


DESCRIPTOR._options = None
_LOGGEDDEVICE_INFOENTRY._options = None
_DEVICE_INFOENTRY._options = None
# @@protoc_insertion_point(module_scope)
