# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/lang.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/lang.proto',
  package='proto.common',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\013ProtoCommon'),
  serialized_pb=_b('\n\x17proto/common/lang.proto\x12\x0cproto.common*(\n\x04Lang\x12\x10\n\x0clang_unknown\x10\x00\x12\x06\n\x02ru\x10\x01\x12\x06\n\x02\x65n\x10\x02\x42\x10P\x01\xa2\x02\x0bProtoCommonb\x06proto3')
)

_LANG = _descriptor.EnumDescriptor(
  name='Lang',
  full_name='proto.common.Lang',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='lang_unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ru', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='en', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=41,
  serialized_end=81,
)
_sym_db.RegisterEnumDescriptor(_LANG)

Lang = enum_type_wrapper.EnumTypeWrapper(_LANG)
lang_unknown = 0
ru = 1
en = 2


DESCRIPTOR.enum_types_by_name['Lang'] = _LANG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
