# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/txauth/tfa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/txauth/tfa.proto',
  package='proto.txauth',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\003FNM'),
  serialized_pb=_b('\n\x16proto/txauth/tfa.proto\x12\x0cproto.txauth\x1a\x1egoogle/protobuf/duration.proto\"\x9a\x01\n\tTFAParams\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12)\n\x07\x63hannel\x18\x03 \x01(\x0e\x32\x18.proto.txauth.TFAChannel\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x03(\t\x12\x31\n\x0e\x64\x65\x61\x64line_after\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration*-\n\nTFAChannel\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03SMS\x10\x01\x12\t\n\x05\x45MAIL\x10\x02\x42\x08P\x01\xa2\x02\x03\x46NMb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])

_TFACHANNEL = _descriptor.EnumDescriptor(
  name='TFAChannel',
  full_name='proto.txauth.TFAChannel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=274,
)
_sym_db.RegisterEnumDescriptor(_TFACHANNEL)

TFAChannel = enum_type_wrapper.EnumTypeWrapper(_TFACHANNEL)
UNKNOWN = 0
SMS = 1
EMAIL = 2



_TFAPARAMS = _descriptor.Descriptor(
  name='TFAParams',
  full_name='proto.txauth.TFAParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='proto.txauth.TFAParams.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='proto.txauth.TFAParams.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='proto.txauth.TFAParams.channel', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='proto.txauth.TFAParams.address', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadline_after', full_name='proto.txauth.TFAParams.deadline_after', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=227,
)

_TFAPARAMS.fields_by_name['channel'].enum_type = _TFACHANNEL
_TFAPARAMS.fields_by_name['deadline_after'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['TFAParams'] = _TFAPARAMS
DESCRIPTOR.enum_types_by_name['TFAChannel'] = _TFACHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TFAParams = _reflection.GeneratedProtocolMessageType('TFAParams', (_message.Message,), {
  'DESCRIPTOR' : _TFAPARAMS,
  '__module__' : 'proto.txauth.tfa_pb2'
  # @@protoc_insertion_point(class_scope:proto.txauth.TFAParams)
  })
_sym_db.RegisterMessage(TFAParams)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
