# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/txauth/token_scope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/txauth/token_scope.proto',
  package='proto.txauth',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\003FNM'),
  serialized_pb=_b('\n\x1eproto/txauth/token_scope.proto\x12\x0cproto.txauth\"C\n\nTokenScope\x12\x12\n\nrestricted\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x03\x12\x10\n\x08readonly\x18\x03 \x01(\x08*\x99\x01\n\x0fTokenContentKey\x12\x15\n\x11TOKEN_CONTENT_ALL\x10\x00\x12\x18\n\x14TOKEN_CONTENT_PERSON\x10\x01\x12\x1a\n\x16TOKEN_CONTENT_FIREBASE\x10\x02\x12\x1a\n\x16TOKEN_CONTENT_ACCOUNTS\x10\x04\x12\x1d\n\x19TOKEN_CONTENT_PERMISSIONS\x10\x08\x42\x08P\x01\xa2\x02\x03\x46NMb\x06proto3')
)

_TOKENCONTENTKEY = _descriptor.EnumDescriptor(
  name='TokenContentKey',
  full_name='proto.txauth.TokenContentKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOKEN_CONTENT_ALL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOKEN_CONTENT_PERSON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOKEN_CONTENT_FIREBASE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOKEN_CONTENT_ACCOUNTS', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOKEN_CONTENT_PERMISSIONS', index=4, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=271,
)
_sym_db.RegisterEnumDescriptor(_TOKENCONTENTKEY)

TokenContentKey = enum_type_wrapper.EnumTypeWrapper(_TOKENCONTENTKEY)
TOKEN_CONTENT_ALL = 0
TOKEN_CONTENT_PERSON = 1
TOKEN_CONTENT_FIREBASE = 2
TOKEN_CONTENT_ACCOUNTS = 4
TOKEN_CONTENT_PERMISSIONS = 8



_TOKENSCOPE = _descriptor.Descriptor(
  name='TokenScope',
  full_name='proto.txauth.TokenScope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restricted', full_name='proto.txauth.TokenScope.restricted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='proto.txauth.TokenScope.content', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readonly', full_name='proto.txauth.TokenScope.readonly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['TokenScope'] = _TOKENSCOPE
DESCRIPTOR.enum_types_by_name['TokenContentKey'] = _TOKENCONTENTKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenScope = _reflection.GeneratedProtocolMessageType('TokenScope', (_message.Message,), {
  'DESCRIPTOR' : _TOKENSCOPE,
  '__module__' : 'proto.txauth.token_scope_pb2'
  # @@protoc_insertion_point(class_scope:proto.txauth.TokenScope)
  })
_sym_db.RegisterMessage(TokenScope)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
