# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos.txauth import txauth_api_pb2 as grpc_dot_txauth_dot_txauth__api__pb2


class TxAuthApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Auth = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/Auth',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.TokenResponse.FromString,
        )
    self.Renew = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/Renew',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.RenewRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.TokenResponse.FromString,
        )
    self.GetLoggedDevices = channel.unary_stream(
        '/grpc.txauth.TxAuthApi/GetLoggedDevices',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.LoggedDevicesRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.LoggedDevicesResponse.FromString,
        )
    self.LogoutDevice = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/LogoutDevice',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.LogoutDeviceRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.LogoutDeviceResponse.FromString,
        )
    self.Providers = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/Providers',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthProvidersRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthProvidersResponse.FromString,
        )
    self.TempLogin = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/TempLogin',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.TempLoginRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.TempLoginResponse.FromString,
        )
    self.OneTimeToken = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/OneTimeToken',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenResponse.FromString,
        )
    self.GetOneTimeToken = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/GetOneTimeToken',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenResponse.FromString,
        )
    self.ExchangeOneTimeToken = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/ExchangeOneTimeToken',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.ExchangeOneTimeTokenRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.ExchangeOneTimeTokenResponse.FromString,
        )
    self.GetAutologinUrl = channel.unary_unary(
        '/grpc.txauth.TxAuthApi/GetAutologinUrl',
        request_serializer=grpc_dot_txauth_dot_txauth__api__pb2.AutologinRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.AutologinResponse.FromString,
        )


class TxAuthApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Auth(self, request, context):
    """
    POST /grpc-json/txauth/v3/auth/{provider}/{login}

    В теле запроса передаются:
    - string password
    - Device device

    Пример:

    POST /grpc-json/txauth/v3/auth/J2T/aivanov
    {
    "password": "Password1!",
    "device": {
    "local_id": "Valeroid",
    "name": "DeviceName",
    "info": {
    "0": "platform"
    }
    }
    }
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Renew(self, request, context):
    """
    POST /grpc-json/txauth/v3/renew

    В теле запроса передаются:
    - string token
    - Device device
    - string code
    - bool force
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLoggedDevices(self, request, context):
    """
    POST /grpc-json/txauth/v3/getloggeddevices
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LogoutDevice(self, request, context):
    """
    DELETE /grpc-json/txauth/v3/logoutdevice/{key_id}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Providers(self, request, context):
    """
    GET /grpc-json/txauth/v3/providers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TempLogin(self, request, context):
    """*
    Deprecated.
    См. TxAuthAdmin#GetTempLogin
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OneTimeToken(self, request, context):
    """deprecated, см. GetOneTimeToken
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOneTimeToken(self, request, context):
    """*
    POST /grpc-json/txauth/v3/getonetimetoken
    см. https://wiki.finam.ru/pages/viewpage.action?pageId=303570863
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeOneTimeToken(self, request, context):
    """
    POST /grpc-json/txauth/v3/exchangeonetimetoken

    В теле запроса передается:
    - string ott token
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAutologinUrl(self, request, context):
    """
    GET /grpc-json/txauth/v3/autologin?route={..}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TxAuthApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Auth': grpc.unary_unary_rpc_method_handler(
          servicer.Auth,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.TokenResponse.SerializeToString,
      ),
      'Renew': grpc.unary_unary_rpc_method_handler(
          servicer.Renew,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.RenewRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.TokenResponse.SerializeToString,
      ),
      'GetLoggedDevices': grpc.unary_stream_rpc_method_handler(
          servicer.GetLoggedDevices,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.LoggedDevicesRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.LoggedDevicesResponse.SerializeToString,
      ),
      'LogoutDevice': grpc.unary_unary_rpc_method_handler(
          servicer.LogoutDevice,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.LogoutDeviceRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.LogoutDeviceResponse.SerializeToString,
      ),
      'Providers': grpc.unary_unary_rpc_method_handler(
          servicer.Providers,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthProvidersRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.AuthProvidersResponse.SerializeToString,
      ),
      'TempLogin': grpc.unary_unary_rpc_method_handler(
          servicer.TempLogin,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.TempLoginRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.TempLoginResponse.SerializeToString,
      ),
      'OneTimeToken': grpc.unary_unary_rpc_method_handler(
          servicer.OneTimeToken,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenResponse.SerializeToString,
      ),
      'GetOneTimeToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetOneTimeToken,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.GetOneTimeTokenResponse.SerializeToString,
      ),
      'ExchangeOneTimeToken': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeOneTimeToken,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.ExchangeOneTimeTokenRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.ExchangeOneTimeTokenResponse.SerializeToString,
      ),
      'GetAutologinUrl': grpc.unary_unary_rpc_method_handler(
          servicer.GetAutologinUrl,
          request_deserializer=grpc_dot_txauth_dot_txauth__api__pb2.AutologinRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__api__pb2.AutologinResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.txauth.TxAuthApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
