# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos.txauth import txauth_pb2 as grpc_dot_txauth_dot_txauth__pb2

class TXAuthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSessionKey = channel.unary_unary(
        '/grpc.txauth.TXAuth/GetSessionKey',
        request_serializer=grpc_dot_txauth_dot_txauth__pb2.SessionKeyRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__pb2.SessionKeyResponse.FromString,
        )
    self.GetSession = channel.unary_unary(
        '/grpc.txauth.TXAuth/GetSession',
        request_serializer=grpc_dot_txauth_dot_txauth__pb2.SessionRequest.SerializeToString,
        response_deserializer=grpc_dot_txauth_dot_txauth__pb2.SessionResponse.FromString,
        )


class TXAuthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSessionKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TXAuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSessionKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionKey,
          request_deserializer=grpc_dot_txauth_dot_txauth__pb2.SessionKeyRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__pb2.SessionKeyResponse.SerializeToString,
      ),
      'GetSession': grpc.unary_unary_rpc_method_handler(
          servicer.GetSession,
          request_deserializer=grpc_dot_txauth_dot_txauth__pb2.SessionRequest.FromString,
          response_serializer=grpc_dot_txauth_dot_txauth__pb2.SessionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.txauth.TXAuth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
