# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/types.proto',
  package='proto.common',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\013ProtoCommon'),
  serialized_pb=_b('\n\x18proto/common/types.proto\x12\x0cproto.common\"\xd8\x01\n\x0c\x44\x65\x63imalValue\x12\x0b\n\x03num\x18\x01 \x01(\x03\x12\x0c\n\x04\x66rac\x18\x02 \x01(\x05\x12/\n\x05scale\x18\x03 \x01(\x0e\x32 .proto.common.DecimalValue.Scale\"|\n\x05Scale\x12\x08\n\x04ZERO\x10\x00\x12\x08\n\x04\x44\x45\x43I\x10\x01\x12\t\n\x05\x43\x45NTI\x10\x02\x12\t\n\x05MILLI\x10\x03\x12\x0b\n\x07MILLI10\x10\x04\x12\x0c\n\x08MILLI100\x10\x05\x12\t\n\x05MICRO\x10\x06\x12\x0b\n\x07MICRO10\x10\x07\x12\x0c\n\x08MICRO100\x10\x08\x12\x08\n\x04NANO\x10\t\"-\n\x0f\x42igDecimalValue\x12\x0b\n\x03num\x18\x01 \x01(\x0c\x12\r\n\x05scale\x18\x02 \x01(\r\"%\n\x07\x44\x65\x63imal\x12\x0b\n\x03num\x18\x01 \x01(\x03\x12\r\n\x05scale\x18\x02 \x01(\rB\x10P\x01\xa2\x02\x0bProtoCommonb\x06proto3')
)



_DECIMALVALUE_SCALE = _descriptor.EnumDescriptor(
  name='Scale',
  full_name='proto.common.DecimalValue.Scale',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECI', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CENTI', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILLI', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILLI10', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILLI100', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICRO', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICRO10', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICRO100', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NANO', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_DECIMALVALUE_SCALE)


_DECIMALVALUE = _descriptor.Descriptor(
  name='DecimalValue',
  full_name='proto.common.DecimalValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='proto.common.DecimalValue.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frac', full_name='proto.common.DecimalValue.frac', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='proto.common.DecimalValue.scale', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DECIMALVALUE_SCALE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=259,
)


_BIGDECIMALVALUE = _descriptor.Descriptor(
  name='BigDecimalValue',
  full_name='proto.common.BigDecimalValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='proto.common.BigDecimalValue.num', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='proto.common.BigDecimalValue.scale', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=306,
)


_DECIMAL = _descriptor.Descriptor(
  name='Decimal',
  full_name='proto.common.Decimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='proto.common.Decimal.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='proto.common.Decimal.scale', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=345,
)

_DECIMALVALUE.fields_by_name['scale'].enum_type = _DECIMALVALUE_SCALE
_DECIMALVALUE_SCALE.containing_type = _DECIMALVALUE
DESCRIPTOR.message_types_by_name['DecimalValue'] = _DECIMALVALUE
DESCRIPTOR.message_types_by_name['BigDecimalValue'] = _BIGDECIMALVALUE
DESCRIPTOR.message_types_by_name['Decimal'] = _DECIMAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DecimalValue = _reflection.GeneratedProtocolMessageType('DecimalValue', (_message.Message,), {
  'DESCRIPTOR' : _DECIMALVALUE,
  '__module__' : 'proto.common.types_pb2'
  # @@protoc_insertion_point(class_scope:proto.common.DecimalValue)
  })
_sym_db.RegisterMessage(DecimalValue)

BigDecimalValue = _reflection.GeneratedProtocolMessageType('BigDecimalValue', (_message.Message,), {
  'DESCRIPTOR' : _BIGDECIMALVALUE,
  '__module__' : 'proto.common.types_pb2'
  # @@protoc_insertion_point(class_scope:proto.common.BigDecimalValue)
  })
_sym_db.RegisterMessage(BigDecimalValue)

Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DECIMAL,
  '__module__' : 'proto.common.types_pb2'
  # @@protoc_insertion_point(class_scope:proto.common.Decimal)
  })
_sym_db.RegisterMessage(Decimal)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
