# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/edox/access/passport_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/edox/access/passport_id.proto',
  package='proto.edox.access',
  syntax='proto3',
  serialized_options=_b('\242\002\nEdoxAccess\252\002\tEdox.Grpc'),
  serialized_pb=_b('\n#proto/edox/access/passport_id.proto\x12\x11proto.edox.access\",\n\nPassportId\x12\x0e\n\x06series\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\tB\x19\xa2\x02\nEdoxAccess\xaa\x02\tEdox.Grpcb\x06proto3')
)




_PASSPORTID = _descriptor.Descriptor(
  name='PassportId',
  full_name='proto.edox.access.PassportId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='series', full_name='proto.edox.access.PassportId.series', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='proto.edox.access.PassportId.number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['PassportId'] = _PASSPORTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PassportId = _reflection.GeneratedProtocolMessageType('PassportId', (_message.Message,), {
  'DESCRIPTOR' : _PASSPORTID,
  '__module__' : 'proto.edox.access.passport_id_pb2'
  # @@protoc_insertion_point(class_scope:proto.edox.access.PassportId)
  })
_sym_db.RegisterMessage(PassportId)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
