# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/edox/access/personal_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/edox/access/personal_data.proto',
  package='proto.edox.access',
  syntax='proto3',
  serialized_options=_b('\242\002\nEdoxAccess\252\002\tEdox.Grpc'),
  serialized_pb=_b('\n%proto/edox/access/personal_data.proto\x12\x11proto.edox.access\x1a\x16google/type/date.proto\"\xd9\x01\n\x0cPersonalData\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12(\n\rdate_of_birth\x18\x04 \x01(\x0b\x32\x11.google.type.Date\x12\x36\n\x06gender\x18\x05 \x01(\x0e\x32&.proto.edox.access.PersonalData.Gender\"+\n\x06Gender\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x42\x19\xa2\x02\nEdoxAccess\xaa\x02\tEdox.Grpcb\x06proto3')
  ,
  dependencies=[google_dot_type_dot_date__pb2.DESCRIPTOR,])



_PERSONALDATA_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='proto.edox.access.PersonalData.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=259,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_PERSONALDATA_GENDER)


_PERSONALDATA = _descriptor.Descriptor(
  name='PersonalData',
  full_name='proto.edox.access.PersonalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='proto.edox.access.PersonalData.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='proto.edox.access.PersonalData.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middle_name', full_name='proto.edox.access.PersonalData.middle_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='proto.edox.access.PersonalData.date_of_birth', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='proto.edox.access.PersonalData.gender', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERSONALDATA_GENDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=302,
)

_PERSONALDATA.fields_by_name['date_of_birth'].message_type = google_dot_type_dot_date__pb2._DATE
_PERSONALDATA.fields_by_name['gender'].enum_type = _PERSONALDATA_GENDER
_PERSONALDATA_GENDER.containing_type = _PERSONALDATA
DESCRIPTOR.message_types_by_name['PersonalData'] = _PERSONALDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonalData = _reflection.GeneratedProtocolMessageType('PersonalData', (_message.Message,), {
  'DESCRIPTOR' : _PERSONALDATA,
  '__module__' : 'proto.edox.access.personal_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.edox.access.PersonalData)
  })
_sym_db.RegisterMessage(PersonalData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
